data_generator:
  type: "MathGenerator"
  params:
    operation: "addition"

llm_provider:
  type: "OpenAIProvider"
  params:
    model: "gpt-3.5-turbo"
    api_key: "YOUR_OPENAI_API_KEY"

framework:
  num_samples: 10